apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app.kubernetes.io/name: app-service
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
  - name: {{ .Values.services.apps.port | quote }}
    port: {{ .Values.services.apps.port }}
    targetPort: {{ .Values.services.apps.port }}
  selector:
    app.kubernetes.io/name: app-service
    app.kubernetes.io/part-of: budibase
status:
  loadBalancer: {}
