{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: budibase
spec:
  commonName: {{ .Values.ingress.common_name }}
  dnsNames:
    - {{ .Values.ingress.dns_names }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.cert_issuer }}
  secretName: budibase-traefik-tls
{{- end }}
