{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: budibase-crt
spec:
  secretName: budibase-crt-secret
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: {{ .Values.ingress.cert_issuer }}
{{- end }}
