{{- if .Values.services.objectStore.minio }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  labels:
    app.kubernetes.io/name: budibase-minio
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: minio
    app.kubernetes.io/managed-by: argocd
  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.objectStore.storage }}
status: {}
{{- end }}