{{- if .Values.services.objectStore.minio }}
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app.kubernetes.io/name: budibase-minio
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: minio
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
  - name: {{ .Values.services.objectStore.port | quote }}
    port: {{ .Values.services.objectStore.port }}
    targetPort: {{ .Values.services.objectStore.port }}
  selector:
    app.kubernetes.io/name: budibase-minio
    app.kubernetes.io/part-of: budibase
{{- end }}