{{- if .Values.services.objectStore.minio }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-service
  labels:
    app.kubernetes.io/name: budibase-minio
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: minio
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: budibase-minio
      app.kubernetes.io/part-of: budibase
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: budibase-minio
        app.kubernetes.io/part-of: budibase
        app.kubernetes.io/component: minio
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_BROWSER
          value: {{ .Values.services.objectStore.browser | quote }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "budibase.fullname" . }}
              key: objectStoreAccess
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "budibase.fullname" . }}
              key: objectStoreSecret
        image: minio/minio
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9000/minio/health/live
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 20
        name: minio-service
        ports:
        - containerPort: {{ .Values.services.objectStore.port }}
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-data
      restartPolicy: Always
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data
{{- end }}