---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.proxy.name }}
  labels:
    app.kubernetes.io/name: budibase-proxy
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: argocd
spec:
  type: {{ .Values.services.proxy.type }}
  ports:
  - name: {{ .Values.services.proxy.port | quote }}
    port: {{ .Values.services.proxy.port }}
    targetPort: {{ .Values.services.proxy.port }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: budibase-proxy
    app.kubernetes.io/part-of: budibase