---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  labels:
    app.kubernetes.io/name: budibase-proxy
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: {{ .Values.services.proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: budibase-proxy
      app.kubernetes.io/part-of: budibase
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: budibase-proxy
        app.kubernetes.io/part-of: budibase
        app.kubernetes.io/component: proxy
        app.kubernetes.io/managed-by: argocd
    spec:
      restartPolicy: Always
      containers:
      - name: proxy-service
        image: budibase/proxy
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.services.proxy.port }}
        volumeMounts:  
        - name: envoy-config
          mountPath: "/etc/envoy"
          readOnly: true
      volumes:
      - name: envoy-config
        configMap:
          name: {{ .Values.services.proxy.name }}-configmap
          items:
          - key: "envoy.yaml"
            path: "envoy.yaml"