apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: budibase-proxy
  name: {{ .Values.services.proxy.name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.services.proxy.port }}
    targetPort: {{ .Values.services.proxy.port }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: budibase-proxy
status:
  loadBalancer: {}
