{{- if .Values.services.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app.kubernetes.io/name: redis-data
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.redis.storage }}
{{- end }}