{{- if .Values.services.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/name: redis-service
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
  - name: {{ .Values.services.redis.port | quote }}
    port: {{ .Values.services.redis.port }}
    targetPort: {{ .Values.services.redis.port }}
  selector:
    
    app.kubernetes.io/name: redis-service
    app.kubernetes.io/part-of: budibase
{{- end }}