apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app.kubernetes.io/name: worker-service
    app.kubernetes.io/part-of: budibase
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
  - name: {{ .Values.services.worker.port | quote }}
    port: {{ .Values.services.worker.port }}
    targetPort: {{ .Values.services.worker.port }}
  selector:
    app.kubernetes.io/name: worker-service
    app.kubernetes.io/part-of: budibase
